name: Deploy to Itch.IO

on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed

jobs:
  deploy-itchio:
    runs-on: ubuntu-latest
    
    needs: build

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64

    steps:
      - uses: actions/checkout@v2
          
      - name: Download a Builded Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: ${{ matrix.targetPlatform }}
          path: build
    
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: ${{ format('zip -r {0}.zip {0}/', matrix.targetPlatform) }}
          
      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Upload ${{ matrix.targetPlatform }} to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/${{ matrix.targetPlatform }}
          project: ${{ secrets.ITCHIO_PROJECT_NAME }}
          channel: ${{ matrix.targetPlatform }}
          version: ${{ matrix.targetPlatform }}.${{ env.version }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
